server:
  port: 8099

spring:
  cloud:
    stream:
      default-binder: rabbit

  application:
    name: chat-service

  # MongoDB ì„¤ì •
  data:
    mongodb:
      uri: mongodb://chunsun:chunsun@localhost:27017/chatdb?authSource=chatdb

  kafka:
    consumer:
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
      #   bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: chat-consumer
      properties:
        spring.json.trusted.packages: "com.chunsun.chatservice.web.dto"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.chunsun.chatconsumer.web.dto.MessageDto
        fetch.min.bytes: 50000  # ìµœì†Œ 50KB ì´ìƒì˜ ë°ì´í„°ê°€ ìŒ“ì—¬ì•¼ ê°€ì ¸ì˜´
        fetch.max.wait.ms: 5000 # 5ì´ˆ ì´ë‚´ì— ë°ì´í„°ê°€ ìŒ“ì´ì§€ ì•Šìœ¼ë©´ ê°€ì ¸ì˜´
      enable-auto-commit: false  # ğŸš€ ë°˜ë“œì‹œ false ì„¤ì • (ìˆ˜ë™ ì»¤ë°‹ì„ ìœ„í•´)
      auto-offset-reset: earliest  # or latest (í•„ìš”ì— ë”°ë¼ ì¡°ì •)
      max-poll-records: 500  # ğŸš€ í•œ ë²ˆì— ê°€ì ¸ì˜¬ ë©”ì‹œì§€ ê°œìˆ˜ ì¡°ì •

eureka:
  client:
    enabled: false