server:
  port: 8089

spring:
  cloud:
    stream:
      default-binder: rabbit

  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: chunsun
    password: chunsun
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29094  # âœ… ë¡œì»¬ì—ì„œë„ kafkaì— ì ‘ê·¼ ê°€ëŠ¥í•˜ë„ë¡ ë³€ê²½
      #   bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # âœ… JSON ì§ë ¬í™”
      properties:
        spring.json.add.type.headers: false  # âœ… JSON íƒ€ì… í—¤ë” ì¶”ê°€ ë¹„í™œì„±í™”


# ğŸ”¥ğŸ”¥docker build í• ë•Œ ì£¼ì„ ì²˜ë¦¬ í•´ì•¼í•¨ğŸ”¥ğŸ”¥
eureka:
  client:
    enabled: false  # Eureka Client ì™„ì „ ë¹„í™œì„±í™”
